# Site Info
title:              "dm-istomin.github.io"
description:        "Software developer blog - little bit of everything, as long as it's tech-related."
google_verify:      # Put your Google Verification here
google_analytics:   UA-73767920-1

# Author Info
author_name:        "Dmitriy Istomin"
author_email:       istomin.dmit@gmail.com
author_gravatar:    3253af63a3e01224ea2d6ef57c5444d5 # Gravatar md5 hash
twitter_username:   dm-istomin

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /notes/:title # Post permalink
timezone:           America/Atikokan # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        pygments
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
